plugins {
    id "maven-publish"
    id "com.android.library"
}

ext {
    versionNumber = "2.1.0"
}

group = 'io.flic'
version = versionNumber

android {
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 36
        versionName versionNumber
        buildConfigField("String", "VERSION_NAME", "\"${versionNumber}\"")

        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig = true
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

    namespace "io.flic.flic2libandroid"
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

tasks.register('androidJavadoc', Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    android.libraryVariants.configureEach { variant ->
        if (variant.name == 'release') {
            classpath += variant.javaCompileProvider.get().classpath
        }
    }
}

tasks.register('androidJavadocJar', Jar) {
    dependsOn androidJavadoc
    archiveClassifier.set('javadoc')
    from androidJavadoc.destinationDir
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = "io.flic"
                artifactId = "flic2lib-android"
                version = versionNumber

                from components.release

                artifact tasks.androidJavadocJar
            }
        }
    }
}
